all: pdf

pdf: iclr-poster.tex question_bank.tex timeline.tex leaderboard_llm_human.tex leaderboard_llm.tex leaderboard_llm_human_combo.tex fri.png
	pdflatex iclr-poster.tex

clean:
	rm -f iclr-poster.aux iclr-poster.log iclr-poster.nav iclr-poster.snm iclr-poster.toc iclr-poster.out iclr-poster.pdf

